name: digital_voucher_indonesia
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hexcolor: ^3.0.1
  # iconsax: ^0.0.8
  fluttertoast: ^8.2.2
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  http:
  flutter_cors: ^1.5.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/logo_new.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21